📑 Rapport Technique : Intelligence Artificielle & Analyse Prédictive📝 Présentation GénéraleCe dépôt regroupe des travaux avancés en Machine Learning et Analyse de Données, articulés autour de deux axes majeurs :Prévision Boursière (Maroc Telecom - IAM) : Modélisation de séries temporelles par régression.Classification Algorithmique : Implémentation et optimisation de modèles supervisés (MLP, AdaBoost).📈 Partie 1 : Projet Maroc Telecom (IAM)🔍 1.1 Objectif et ContexteL'objectif est de prédire le cours de clôture de l'action IAM à partir de données historiques. Le projet ne se contente pas des prix bruts, il enrichit le dataset avec de l'Analyse Technique.🛠 1.2 Feature Engineering (Ingénierie des Caractéristiques)Le code utilise la bibliothèque ta pour transformer les prix en signaux mathématiques :RSI (Relative Strength Index) : Mesure la vitesse et le changement des mouvements de prix pour identifier le surachat ou la survente.Moyennes Mobiles (SMA/EMA) : Lissent les fluctuations pour identifier la tendance de fond.Bandes de Bollinger : Évaluent la volatilité du marché.💻 1.3 Analyse du Modèle de RégressionLe script compare plusieurs algorithmes. Le Gradient Boosting Regressor a été retenu comme modèle final.Pourquoi le Gradient Boosting ?Contrairement à une simple régression linéaire, le Gradient Boosting construit des arbres de décision de manière séquentielle. Chaque nouvel arbre tente de minimiser l'erreur (le résidu) laissée par les arbres précédents.$$Loss = \sum (y_i - \hat{y}_i)^2$$Python# Configuration du modèle Champion
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(
    n_estimators=100, # Nombre d'arbres séquentiels
    learning_rate=0.1, # Vitesse d'ajustement
    max_depth=3,       # Limite la complexité pour éviter l'overfitting
    random_state=42
)
model.fit(X_train, y_train)
📊 1.4 Résultats de PerformanceLes métriques obtenues sont exceptionnelles, suggérant une très haute fiabilité sur les données de test :MétriqueValeurSignificationR² (Score)<font color="green">0.9996</font>99.9% de la variance est expliquée par le modèle.RMSE0.2449 MADÉcart type moyen des erreurs de prédiction.MAE0.1884 MADErreur absolue moyenne (très faible).Prévision à J+60 : Le modèle projette un cours cible de 108.82 MAD.🧬 Partie 2 : Algorithmes de ClassificationCe volet valide la robustesse des modèles de classification sur des datasets standards (Iris, Breast Cancer).🧠 2.1 Perceptron Multicouche (MLP)Le MLP est un réseau de neurones artificiels. Le code implémente une structure capable de séparer des classes non-linéaires.Fonctionnement : Les données passent par des couches cachées où des poids sont appliqués, suivis d'une fonction d'activation (souvent ReLU).Résultat : Une précision de 100% (Accuracy: 1.0) sur le dataset Iris.⚡ 2.2 AdaBoost (Adaptive Boosting)Le boosting consiste à combiner des "apprenants faibles" pour créer un "apprenant fort".Pythonfrom sklearn.ensemble import AdaBoostClassifier

# Initialisation d'AdaBoost avec 100 estimateurs
ada = AdaBoostClassifier(n_estimators=100, learning_rate=0.5)
ada.fit(X_train, y_train)
Analyse technique : AdaBoost ajuste les poids des instances à chaque étape. Les exemples mal classés par le premier arbre reçoivent un poids plus important pour le second arbre, forçant le modèle à se concentrer sur les cas difficiles.📁 3. Structure des Fichiers SortiesLe projet génère automatiquement des rapports visuels pour faciliter l'interprétation :IAM_01_Analyse_Technique.png : Visualisation des prix et indicateurs.IAM_03_Comparaison_Modeles.png : Graphique comparatif des erreurs (MAE/RMSE).IAM_04_Predictions_Futures.png : Courbe de tendance prédictive à 60 jours.🛠 4. Installation et DépendancesPour reproduire ces résultats, les bibliothèques suivantes sont nécessaires :Bashpip install pandas numpy matplotlib scikit-learn ta seaborn
📌 ConclusionCe travail démontre l'efficacité du Machine Learning appliqué à la finance. Le modèle de Gradient Boosting permet une précision quasi-chirurgicale sur le titre IAM, tandis que les implémentations de réseaux de neurones et de Boosting confirment la maîtrise des concepts fondamentaux de la classification supervisée.Note : Ce rapport a été généré automatiquement pour documenter les notebooks Projet_IAM_S8.ipynb et algorithmes_corrigés.ipynb.
